name: CI/CD - Deploy Azure

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          cache: true
          cache-dependency-path: "**/*.csproj"

      - name: Restore
        working-directory: src
        run: dotnet restore BugStore.sln

      - name: Build (Release)
        working-directory: src
        run: dotnet build BugStore.sln --configuration Release --no-restore

      - name: Test
        working-directory: src
        run: dotnet test BugStore.sln --configuration Release --no-build --verbosity normal

      - name: Publish
        working-directory: src
        run: dotnet publish BugStore.Api/BugStore.Api.csproj --configuration Release --no-build -o ./publish -p:UseAppHost=false

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: bugstore-api
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./src/publish
